production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  clients:
    default:
      database: backend_development
      hosts:
        - localhost:27017
      options:
        # Optional MongoDB Ruby driver settings

  options:
    # Mongoid-specific options

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1