production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        ssl: true
        server_selection_timeout: 5

development:
  clients:
    default:
      database: backend_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
        server_selection_timeout: 5
